# Generated by Django 4.0.5 on 2022-06-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
