# Generated by Django 4.0.5 on 2022-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
